### ISSUE TITLE
Fix Navigation Bar on index page

### ISSUE THREAD

**Issue by pena56** [solomoreal/slash-hack-2.0#1]
Navigation Bar does not render properly when viewed online.

**Comment by ikeogu** [comment]
how do you mean Mr Moses , but it was working fine on friday nah

**Comment by pena56** [comment]
i previewed the index page on github and it rendered a little a differently than when we previewed it locally

**Comment by ikeogu** [comment]
let me  check it

**Comment by ikeogu** [comment]
it is working very fine

**Comment by ikeogu** [comment]
push your own work for me to pull and edit and push back
